#ifndef OBJECT_H
#define OBJECT_H

#include "db.h"
#include "geometry.h"
#include "inventory.h"
#include "map_defs.h"
#include "obj_types.h"

typedef struct ObjectWithFlags {
    int flags;
    Object* object;
} ObjectWithFlags;

extern bool gObjectsInitialized;
extern int dword_5195FC;
extern int dword_519600;
extern int dword_519604;
extern int* off_519608[2];
extern int* off_519610[2];
extern int* off_51961C;
extern int* off_519618;
extern ObjectListNode** off_519620;
extern int dword_519624;
extern ObjectListNode* gObjectListHead;
extern int dword_51962C;
extern int gObjectFindElevation;
extern int gObjectFindTile;
extern ObjectListNode* gObjectFindLastObjectListNode;
extern int* gObjectFids;
extern int gObjectFidsLength;
extern Rect stru_51964C[9];
extern int dword_5196DC[36];
extern int gViolenceLevel;
extern int dword_519770;
extern int dword_519774;
extern int dword_519778;
extern int dword_51977C;
extern unsigned char* dword_519780;
extern unsigned char* dword_519784;
extern unsigned char* dword_519788;
extern unsigned char* dword_51978C;
extern unsigned char* dword_519790;
extern Object* off_519794;
extern int dword_519798;
extern int dword_51979C[9];

extern int dword_6391D0[6][36];
extern int dword_639530[2][6][36];
extern Rect gObjectsWindowRect;
extern Object* off_639C00[100];
extern int dword_639D90;
extern int dword_639D94;
extern int dword_639D98;
extern int dword_639D9C;
extern ObjectListNode* gObjectListHeadByTile[HEX_GRID_SIZE];
extern unsigned char byte_660EA0[256];
extern unsigned char byte_660FA0[256];
extern int gObjectsWindowBufferSize;
extern unsigned char* gObjectsWindowBuffer;
extern int gObjectsWindowHeight;
extern Object* gEgg;
extern int gObjectsWindowPitch;
extern int gObjectsWindowWidth;
extern Object* gDude;
extern char byte_6610BC[5001];
extern char byte_662445[5001];

int objectsInit(unsigned char* buf, int width, int height, int pitch);
void objectsReset();
void objectsExit();
int objectRead(Object* obj, File* stream);
int objectLoadAll(File* stream);
int objectLoadAllInternal(File* stream);
void sub_48909C();
void sub_48911C(Object* obj);
int objectWrite(Object* obj, File* stream);
int objectSaveAll(File* stream);
void sub_489550(Rect* rect, int elevation);
void sub_4897EC(Rect* rect, int elevation);
int objectCreateWithFidPid(Object** objectPtr, int fid, int pid);
int objectCreateWithPid(Object** objectPtr, int pid);
int sub_489CCC(Object** a1, Object* a2);
int sub_489EC4(Object* obj, int tile_index, int elev, Rect* rect);
int sub_489F34(Object* obj, Rect* rect);
int sub_489FF8(Object* obj, int x, int y, Rect* rect);
int sub_48A324(Object* a1, int a2, int a3, int elevation, Rect* a5);
int objectSetLocation(Object* obj, int tile, int elevation, Rect* rect);
int sub_48A9A0();
int objectSetFid(Object* obj, int fid, Rect* rect);
int objectSetFrame(Object* obj, int frame, Rect* rect);
int objectSetNextFrame(Object* obj, Rect* rect);
int objectSetPrevFrame(Object* obj, Rect* rect);
int objectSetRotation(Object* obj, int direction, Rect* rect);
int objectRotateClockwise(Object* obj, Rect* rect);
int objectRotateCounterClockwise(Object* obj, Rect* rect);
void sub_48AC54();
int objectSetLight(Object* obj, int lightDistance, int lightIntensity, Rect* rect);
int objectGetLightIntensity(Object* obj);
int sub_48AD48(Object* obj, Rect* rect);
int sub_48AD9C(Object* obj, Rect* rect);
int objectShow(Object* obj, Rect* rect);
int objectHide(Object* obj, Rect* rect);
int objectEnableOutline(Object* obj, Rect* rect);
int objectDisableOutline(Object* obj, Rect* rect);
int sub_48AF2C(Object* obj, Rect* rect);
int objectDestroy(Object* a1, Rect* a2);
int sub_48B1B0(Inventory* inventory);
bool sub_48B24C(Object* obj);
bool sub_48B278(Object* obj);
bool sub_48B2A8(Object* obj);
Object* objectFindById(int a1);
Object* objectGetOwner(Object* obj);
void sub_48B318();
Object* objectFindFirst();
Object* objectFindNext();
Object* objectFindFirstAtElevation(int elevation);
Object* objectFindNextAtElevation();
Object* objectFindFirstAtLocation(int elevation, int tile);
Object* objectFindNextAtLocation();
void objectGetRect(Object* obj, Rect* rect);
bool sub_48B7F8(int tile_num, int elev);
Object* sub_48B848(Object* a1, int tile_num, int elev);
Object* sub_48B930(Object* obj, int tile, int elev);
Object* sub_48BA20(Object* a1, int tile, int elevation);
int sub_48BB44(int tile_num, int elev);
Object* sub_48BB88(Object* a1, int tile_num, int elev);
int objectGetDistanceBetween(Object* object1, Object* object2);
int objectGetDistanceBetweenTiles(Object* object1, int tile1, Object* object2, int tile2);
int objectListCreate(int tile, int elevation, int objectType, Object*** objectsPtr);
void objectListFree(Object** objects);
void sub_48BDD8(unsigned char* src, int srcWidth, int srcHeight, int srcPitch, unsigned char* dest, int destX, int destY, int destPitch, unsigned char* a9, unsigned char* a10);
void sub_48BEFC(unsigned char* src, int srcWidth, int srcHeight, int srcPitch, unsigned char* dest, int destX, int destY, int destPitch, int light);
void sub_48BF88(unsigned char* src, int srcWidth, int srcHeight, int srcPitch, unsigned char* dest, int destX, int destY, int destPitch, int light, unsigned char* a10, unsigned char* a11);
void sub_48C03C(unsigned char* src, int srcWidth, int srcHeight, int srcPitch, unsigned char* dest, int destPitch, unsigned char* mask, int maskPitch, int light);
int objectSetOutline(Object* obj, int a2, Rect* rect);
int objectClearOutline(Object* obj, Rect* rect);
int sub_48C340(Object* object, int x, int y);
int sub_48C5C4(int x, int y, int elevation, int objectType, ObjectWithFlags** entriesPtr);
void sub_48C74C(ObjectWithFlags** a1);
void sub_48C788();
void sub_48C7A0();
char* objectGetName(Object* obj);
char* objectGetDescription(Object* obj);
void sub_48C938(int flags);
int sub_48CB88();
void sub_48CDA0();
int sub_48CE10();
int sub_48CF20(const void* a1, const void* a2);
int sub_48CF38(const void* a1, const void* a2);
void sub_48CF50();
int sub_48CF8C();
void sub_48D000();
void sub_48D020();
void sub_48D1E4();
void sub_48D2E8();
int sub_48D348(File* stream, Object* object);
int sub_48D414(File* stream, Object** objectPtr, int elevation, Object* owner);
int sub_48D59C(File* stream);
int sub_48D600(File* stream);
int objectAllocate(Object** objectPtr);
void objectDeallocate(Object** objectPtr);
int objectListNodeCreate(ObjectListNode** nodePtr);
void objectListNodeDestroy(ObjectListNode** nodePtr);
int objectGetListNode(Object* obj, ObjectListNode** out_node, ObjectListNode** out_prev_node);
void sub_48D8E8(ObjectListNode* ptr);
int sub_48DA58(ObjectListNode* a1, ObjectListNode* a2);
int sub_48DB28(ObjectListNode* node, int tile_index, int elev, Rect* rect);
int sub_48DC28(Object* obj, int a2, Rect* rect);
void objectDrawOutline(Object* object, Rect* rect);
void sub_48F1B0(Object* object, Rect* rect, int light);
void sub_48FA14(int* fid);
int sub_48FB08(const void* a1, const void* a2);

#endif /* OBJECT_H */
