#ifndef OBJECT_H
#define OBJECT_H

#include "db.h"
#include "geometry.h"
#include "inventory.h"
#include "map_defs.h"
#include "obj_types.h"

typedef struct ObjectWithFlags {
    int flags;
    Object* object;
} ObjectWithFlags;

extern bool gObjectsInitialized;
extern int dword_5195FC;
extern int dword_519600;
extern int dword_519604;
extern int* off_519608[2];
extern int* off_519610[2];
extern int* off_51961C;
extern int* off_519618;
extern ObjectListNode** off_519620;
extern int dword_519624;
extern ObjectListNode* gObjectListHead;
extern int dword_51962C;
extern int gObjectFindElevation;
extern int gObjectFindTile;
extern ObjectListNode* gObjectFindLastObjectListNode;
extern int* gObjectFids;
extern int gObjectFidsLength;
extern Rect stru_51964C[9];
extern int dword_5196DC[36];
extern int gViolenceLevel;
extern int dword_519770;
extern int dword_519774;
extern int dword_519778;
extern int dword_51977C;
extern unsigned char* dword_519780;
extern unsigned char* dword_519784;
extern unsigned char* dword_519788;
extern unsigned char* dword_51978C;
extern unsigned char* dword_519790;
extern Object* off_519794;
extern int dword_519798;
extern int dword_51979C[9];

extern int dword_6391D0[6][36];
extern int dword_639530[2][6][36];
extern Rect gObjectsWindowRect;
extern Object* off_639C00[100];
extern int dword_639D90;
extern int dword_639D94;
extern int dword_639D98;
extern int dword_639D9C;
extern ObjectListNode* gObjectListHeadByTile[HEX_GRID_SIZE];
extern unsigned char byte_660EA0[256];
extern unsigned char byte_660FA0[256];
extern int gObjectsWindowBufferSize;
extern unsigned char* gObjectsWindowBuffer;
extern int gObjectsWindowHeight;
extern Object* gEgg;
extern int gObjectsWindowPitch;
extern int gObjectsWindowWidth;
extern Object* gDude;
extern char byte_6610BC[5001];
extern char byte_662445[5001];

int objectsInit(unsigned char* buf, int width, int height, int pitch);
void objectsReset();
void objectsExit();
int objectRead(Object* obj, File* stream);
int objectLoadAll(File* stream);
int objectLoadAllInternal(File* stream);
void obj_fix_combat_cid_for_dude();
void object_fix_weapon_ammo(Object* obj);
int objectWrite(Object* obj, File* stream);
int objectSaveAll(File* stream);
void obj_render_pre_roof(Rect* rect, int elevation);
void obj_render_post_roof(Rect* rect, int elevation);
int objectCreateWithFidPid(Object** objectPtr, int fid, int pid);
int objectCreateWithPid(Object** objectPtr, int pid);
int obj_copy(Object** a1, Object* a2);
int obj_connect(Object* obj, int tile_index, int elev, Rect* rect);
int obj_disconnect(Object* obj, Rect* rect);
int obj_offset(Object* obj, int x, int y, Rect* rect);
int obj_move(Object* a1, int a2, int a3, int elevation, Rect* a5);
int objectSetLocation(Object* obj, int tile, int elevation, Rect* rect);
int obj_reset_roof();
int objectSetFid(Object* obj, int fid, Rect* rect);
int objectSetFrame(Object* obj, int frame, Rect* rect);
int objectSetNextFrame(Object* obj, Rect* rect);
int objectSetPrevFrame(Object* obj, Rect* rect);
int objectSetRotation(Object* obj, int direction, Rect* rect);
int objectRotateClockwise(Object* obj, Rect* rect);
int objectRotateCounterClockwise(Object* obj, Rect* rect);
void obj_rebuild_all_light();
int objectSetLight(Object* obj, int lightDistance, int lightIntensity, Rect* rect);
int objectGetLightIntensity(Object* obj);
int obj_turn_on_light(Object* obj, Rect* rect);
int obj_turn_off_light(Object* obj, Rect* rect);
int objectShow(Object* obj, Rect* rect);
int objectHide(Object* obj, Rect* rect);
int objectEnableOutline(Object* obj, Rect* rect);
int objectDisableOutline(Object* obj, Rect* rect);
int obj_toggle_flat(Object* obj, Rect* rect);
int objectDestroy(Object* a1, Rect* a2);
int obj_inven_free(Inventory* inventory);
bool obj_action_can_use(Object* obj);
bool obj_action_can_talk_to(Object* obj);
bool obj_portal_is_walk_thru(Object* obj);
Object* objectFindById(int a1);
Object* objectGetOwner(Object* obj);
void obj_remove_all();
Object* objectFindFirst();
Object* objectFindNext();
Object* objectFindFirstAtElevation(int elevation);
Object* objectFindNextAtElevation();
Object* objectFindFirstAtLocation(int elevation, int tile);
Object* objectFindNextAtLocation();
void objectGetRect(Object* obj, Rect* rect);
bool obj_occupied(int tile_num, int elev);
Object* obj_blocking_at(Object* a1, int tile_num, int elev);
Object* obj_shoot_blocking_at(Object* obj, int tile, int elev);
Object* obj_ai_blocking_at(Object* a1, int tile, int elevation);
int obj_scroll_blocking_at(int tile_num, int elev);
Object* obj_sight_blocking_at(Object* a1, int tile_num, int elev);
int objectGetDistanceBetween(Object* object1, Object* object2);
int objectGetDistanceBetweenTiles(Object* object1, int tile1, Object* object2, int tile2);
int objectListCreate(int tile, int elevation, int objectType, Object*** objectsPtr);
void objectListFree(Object** objects);
void translucent_trans_buf_to_buf(unsigned char* src, int srcWidth, int srcHeight, int srcPitch, unsigned char* dest, int destX, int destY, int destPitch, unsigned char* a9, unsigned char* a10);
void dark_trans_buf_to_buf(unsigned char* src, int srcWidth, int srcHeight, int srcPitch, unsigned char* dest, int destX, int destY, int destPitch, int light);
void dark_translucent_trans_buf_to_buf(unsigned char* src, int srcWidth, int srcHeight, int srcPitch, unsigned char* dest, int destX, int destY, int destPitch, int light, unsigned char* a10, unsigned char* a11);
void intensity_mask_buf_to_buf(unsigned char* src, int srcWidth, int srcHeight, int srcPitch, unsigned char* dest, int destPitch, unsigned char* mask, int maskPitch, int light);
int objectSetOutline(Object* obj, int a2, Rect* rect);
int objectClearOutline(Object* obj, Rect* rect);
int obj_intersects_with(Object* object, int x, int y);
int obj_create_intersect_list(int x, int y, int elevation, int objectType, ObjectWithFlags** entriesPtr);
void obj_delete_intersect_list(ObjectWithFlags** a1);
void obj_clear_seen();
void obj_process_seen();
char* objectGetName(Object* obj);
char* objectGetDescription(Object* obj);
void obj_preload_art_cache(int flags);
int obj_offset_table_init();
void obj_offset_table_exit();
int obj_order_table_init();
int obj_order_comp_func_even(const void* a1, const void* a2);
int obj_order_comp_func_odd(const void* a1, const void* a2);
void obj_order_table_exit();
int obj_render_table_init();
void obj_render_table_exit();
void obj_light_table_init();
void obj_blend_table_init();
void obj_blend_table_exit();
int obj_save_obj(File* stream, Object* object);
int obj_load_obj(File* stream, Object** objectPtr, int elevation, Object* owner);
int obj_save_dude(File* stream);
int obj_load_dude(File* stream);
int objectAllocate(Object** objectPtr);
void objectDeallocate(Object** objectPtr);
int objectListNodeCreate(ObjectListNode** nodePtr);
void objectListNodeDestroy(ObjectListNode** nodePtr);
int objectGetListNode(Object* obj, ObjectListNode** out_node, ObjectListNode** out_prev_node);
void obj_insert(ObjectListNode* ptr);
int obj_remove(ObjectListNode* a1, ObjectListNode* a2);
int obj_connect_to_tile(ObjectListNode* node, int tile_index, int elev, Rect* rect);
int obj_adjust_light(Object* obj, int a2, Rect* rect);
void objectDrawOutline(Object* object, Rect* rect);
void obj_render_object(Object* object, Rect* rect, int light);
void obj_fix_violence_settings(int* fid);
int obj_preload_sort(const void* a1, const void* a2);

#endif /* OBJECT_H */
