name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Cache cmake build
        uses: actions/cache@v3
        with:
          path: build
          key: windows-x86-cmake-v1

      - name: Configure
        run: |
          cmake \
            -B build \
            -G "Visual Studio 16 2019" \
            -A Win32 \
            # EOL

      - name: Build
        run: |
          cmake \
            --build build \
            --config RelWithDebInfo \
            # EOL

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: fallout2-re
          path:  build/RelWithDebInfo/fallout2-re.exe
          retention-days: 7
